---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-kagent.yaml
  - helmrepository-kagent.yaml
  - helmrelease-kagent-crds.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kagent
      app.kubernetes.io/managed-by: flux
