apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:XwbYz/92vZKarrsu/Yfmo7kssfMtnBkB8+mlC9yXS5heDb/DHq9QTauwVANJ3C3heje5dhwpZM4DY7vZXoVjRl7Ac774teENkQMBkTYMyovYsf5gcY+7zAogBm8HU2WOQ8p0d9uW/j5XeNGrY1A8vjHvoMegV1kHHjDlBHnt2Srb3tiuL1BJd9wIHlSnYbuJnxDCzIzUu3uECAqkb6ychvgqGRtA/Ppeo4jIWH7x3QRQTrkPCPWzU6blfkJP,iv:4y2iPfP/JLr5h1oTCtbpAKF8ZsJn+NvaNhxVyCLfFwE=,tag:9pWcOEndlZTpMFKASp0g6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTHZmNHl6VDdZRmNHaFpG
            REg2VGJUdGhidFJ1a003Rml2K1VLaDBhbUQwCmFWcGY1a09MeVFtQzRqU0JaWE5E
            VnJDSWVvSy9STGlFWUs4RE9EZVBXOXcKLS0tIGh1V29ldXE0S0hSUjVwNlgzaU1L
            YnBuSW5qZ2Era2VpRjAydmttZng2NXcK8CkUnw1RUFAzrhUCZXTS9ONGSMBamj/c
            es3ZqzsbH1DnU0A2fZb9a3WeJdz065gYj5fBFPaHqIg2Lqg3he7+rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142yu9a74xm8vfls25jvmdvw0c3yrcsvdht0ah9yu8cysya2qqyaqmg6y0a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T13:42:25Z"
    mac: ENC[AES256_GCM,data:TbA2uoSZAh+pZSrMLpNr92aWRCn9nGKhDHTU/OLJTdQEtMYB73I71K1iZYLbQgiUfe/NN/+Pv/WRVniVbcai54345zvUPtbSS1rxTu3BbSjdqs5LYG6aKVNeb+09PpoAfIzQYVt+YjJi14n5o0yBsUqcEK5oqTvuVkfqqZhSZj4=,iv:W1ciz2sqIyuSzAuFYv/0GUEdikHOwVuuHRI678vpu20=,tag:mdp1Cmzt9Kj8i+sWde5mhA==,type:str]
    version: 3.13.1
