apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:NzomvNkWQw+04HkCjyr9nAzBZkim,iv:AiCBADBCUuBWQvvJTMDc183+TH/Jb4iiOvorFE5PKqQ=,tag:3DIgLxSp7e1aDzjwpn2v/w==,type:str]
    password: ENC[AES256_GCM,data:ISO/v+L8b59K4iwiV4LhinOs0lOEdVRDTyebOTnwbin3YzHN9kk0mw==,iv:cmERS4c6nskTBpIzF5E3LXL+I9g69uKNlNRl4YdH3d4=,tag:N8BPx/XFlnIfxNA9fwfkJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLclh2clBpYXh4dFhQUFlQ
            Mm1uQWlzNU52UExiYURMZzFaUDNVRG0yOW1BCjh4NkJmbSt1ZC9PcUFZL2xtenk2
            ZlZzSTFBeGYxUjZvMTdPY3hYQlVvbVkKLS0tIG56Sk1rd2Z4WHE1MGY5azZjOEdK
            Vlg0WTlTM1dSVWhqNzd2SWYxakZXUG8KvdpgTNOySPNfhPw91GQgeAHkCWCgCJ3y
            wpQJSd4iqpvbU1cmYFV7KD1LzGd2KWYejay8G3mksfDsIUOPeIZzzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142yu9a74xm8vfls25jvmdvw0c3yrcsvdht0ah9yu8cysya2qqyaqmg6y0a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T13:42:45Z"
    mac: ENC[AES256_GCM,data:vdfYqmyCzvmJMTPctBIYhAVrxFbienrAVK5tf4cq6FPITonXARD685n3caoscJEuq4aCsf09+NaplOf72/VnWjvPqQWqdNqNBv8wLMJLlYgH5AE0AAcMhRQjDiC8FqG64pRMDniWITOAJFHFs3KYxktOxbSZVMFSjacGbxvBzb4=,iv:WMgzIU4HeRXTV8+r0KI+9SJX1gLTsfnK0CnNPey3wlA=,tag:FG9r7fNjECzwg9sZ1XyQHQ==,type:str]
    version: 3.13.1
