---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-openshell.yaml
  - helmrepository-openshell.yaml
  - helmrelease-openshell.yaml

labels:
  - pairs:
      app.kubernetes.io/name: openshell
      app.kubernetes.io/managed-by: flux
