---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-openclaw-system.yaml
  - helmrepository-openclaw.yaml
  - helmrelease-openclaw-operator.yaml

labels:
  - pairs:
      app.kubernetes.io/name: openclaw-operator
      app.kubernetes.io/managed-by: flux
