# Plain text secret for SOPS encryption
# IMPORTANT: Replace CLOUDFLARE_TUNNEL_TOKEN with your actual Cloudflare Tunnel token
# Encrypt with: sops -e -i secret-cloudflared.yaml
# Decrypt with: sops -d secret-cloudflared.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: edatw
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:324Hr1vdgIBzuAlPaTmhHTW6JcVq4vh8fnCULm3Pb7Vazzl+g5HtcZcSEo0fcFmJEh45mdxWRzPmWTF9mc2NKJZHgPJus2wzmUI4rR1zlv4F9yd94ICPYNMTUS0LEeistznCu1fQR8bTyxHW8K3BuGSlIuwS2AKA/DSYyOO8fJdMBovVm1vWGQtsUsl1ESK0ewDLRStCYjkKO2/Orfr/G99ooIqUw9r50tk0FVmQqiH579+3,iv:9UrpVRcv227BqD2XrYHer3vEYTGwnzdIWYiaenm8HBk=,tag:uPphxkwt6W6nCx1inWebCw==,type:str]
sops:
    age:
        - recipient: age16t62g0jhay0hptsa9t5hlueqdekzqy39rlrzz7qkm29ym2t5jamswdp2px
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGxKeE0rRVNKTFMyVWo5
            T2hSQm9od2JpdkJ4VGtucXNVSGZaL0k3TnkwCnFIeWVvWDdiSzN6NVF5ZGU3MmpY
            SGhlQ3FaTUtnSmRrZmt6RnlYZkdGcVEKLS0tIGNzaENncER1bVY5bWJ3VzdkYno4
            SUlNWmpwNWFpMUJPeldNZ2IrdXljVkUKUzT/JNe+5cjF0qwVv3Bb8R1oks38UgDG
            izCPn48Kx1wx7Wgh1vgRTHpLKx9UcHDjNs+CSPQX4zVXGv7aLDUEjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T17:49:12Z"
    mac: ENC[AES256_GCM,data:G0jRK6/PCjMVh4A6FI4OZYppHNdYfAmlnwXhOD0faDjz0s33EDabwCCf8AsfX7kTFqL4r5IywoLACLlC/wuwT5xZMJn9syUo2S5XunSn4dvbH/GjmJNTIdIoHILWIiSUCXwBRC6U/3KZ8a7i/zwv6Ig0+GxUA6FWcpSXsD2Y+K4=,iv:cEHFDYXypfi/Xu7vYfvHqdReURPwJyD+mR1xlS0ZDwA=,tag:XYz3G7z4SEc19ovTkS0M6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
