apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd
type: Opaque
stringData:
    keys.txt: ENC[AES256_GCM,data:qcxSfJ/G6xUjLdUn81QEQPJ/vud9L7cofC6YFYylPBXDeZYkqbyKI1iUpXtLawL6HVJneCDnXcucVQTf38BoUDJL3teHEJJ1L8V5bp0fTlNFP+g0088XjEAtvYoQ6qdDIVFgBS+J1eNrPTK3EYnAZR6cfN9OkMCFu0yXM5QmfyAqDHPP46FlEYY5p5Lf8RBgJLPUmrvNJJqfZe06lbCQGAZDEQB2BuAUcXcRx34WNGlIWM3GUuhmPCTp2ZaK,iv:Y9ihp/pw9qOh+shJ9ra44fPSPJup71f35b/q9qU5kco=,tag:veCh0CKKxWCx47pGyZ61lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMzVqalZPclU4L29SSFpv
            bEtQL3ZJOW54aVhPaU85dlRVcjJFWmU1VEg0Ck9rQkg1Ris0RlpOSmtEL0djeWly
            dWxwbTNGc0lTQlpTemp3Q0N2ZFdOSVUKLS0tIEx5VW9ORWlVekdhL05SVkdUeDFN
            dkxmM0FDN1dSeEhDdkRIR3k5L1lBaVUKu4iPn5OQAOs+5isx/TAdHDB++IRh1LiZ
            OOubvolTTXusliCxz6k1WuT3KXkEyzCpwM7E4qV+oLc3GcQUoPNWxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142yu9a74xm8vfls25jvmdvw0c3yrcsvdht0ah9yu8cysya2qqyaqmg6y0a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T14:05:39Z"
    mac: ENC[AES256_GCM,data:984vn6Ooc778dnvAKWhJCVosMe+GLfuAcClYukw2CD88B9PdtdeZ33uCa5teqLGk/1UtHCTt2cWLlVEpZv/VLlmcxQuJPC+GePvWXzHk7Leylf+d7+1w5qk9OSS4TZ9X7ed4dlAy5U0+EygMGPeFVPa22iZa5v9dLLDtM6L9vO4=,iv:dkYXBmwh3TRWUuVLppBWriywQ9XzP/lwNArXJosk71U=,tag:wyE0EXrga9p///NpGYhvuw==,type:str]
    version: 3.13.1
