apiVersion: v1
kind: PersistentVolume
metadata:
    annotations:
        pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    name: edatw-ed8-data
spec:
    storageClassName: edatw-eda-smb
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - dir_mode=0750
        - file_mode=0640
        - uid=33
        - gid=33
    csi:
        driver: smb.csi.k8s.io
        readOnly: false
        volumeHandle: ENC[AES256_GCM,data:FcOv+V4FJggCswAsRIj27s3/ySwyunTVBeru,iv:SDDZmSC+wtP8EVfOdbc1sVsxSmsO3MZkpWPM2tSqjJ8=,tag:PwUCMOqo9EQU0qDRgDebUQ==,type:str]
        volumeAttributes:
            source: ENC[AES256_GCM,data:fnJhtuGwF+x1pbccGioGsrTHquKOVLi6rgGrBQ==,iv:Gtcmv46zXGy2Y9IDprIuGPXw+MCiAi0bxYTcKsSkCQU=,tag:f+C6d54u2cu6dRVB0MPfIw==,type:str]
        nodeStageSecretRef:
            name: ed8-creds
            namespace: edatw-ed8
    claimRef:
        name: edatw-ed8-data
        namespace: edatw-ed8
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQnBKSXNaSWthSzc1N1FX
            eHh0R0h0RGFTL1owWVhmUDd3MnhLN2gwT0FrCnZ3ZERXRGlIOXdGY3BNWFVPNUdY
            bkwyMTFla0gyYUNrWnF1eUxGS2x5RWMKLS0tIEJGbnJtVkxGOENRNmw2ZzNQNWxx
            dzIxZURZTTVJc283eTNnRGFhT0ZNMzgKmMnLliCc6NXhXpfna/LvSYor1lrc2XL/
            oRVJsHe21fQ59Yt5HD+sUM3a2Xdhqptv8QT08F6WOP32c/MgI6qfPg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(volumeHandle|source)$
    lastmodified: "2026-06-18T01:36:24Z"
    mac: ENC[AES256_GCM,data:YYvtyzsXAhIejbVwMItS1PdRhLd2UISvXlbskogF6LK6h/JDgHdvYem64Ud/xpI4odU+lg7BfElszfSpmIpeNWwYgwsNPVijhfqY3wpr3B5mlLJrxI7C9LtDAr8O6KYV6mIGgbdYljK1CWFEc5HVkvGAlUmgihxrdQUSJd0IPlw=,iv:akq3oJp71CZkskZ9ahattuwhIwiEVrDMre0y3YTO0qM=,tag:n1ZDSD3YDlwknZm6wUPWuA==,type:str]
    version: 3.13.1
