apiVersion: v1
kind: PersistentVolume
metadata:
    annotations:
        pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    name: edatw-ed8-backups
spec:
    storageClassName: edatw-eda-smb
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - dir_mode=0770
        - file_mode=0660
        - uid=999
        - gid=999
    csi:
        driver: smb.csi.k8s.io
        readOnly: false
        volumeHandle: ENC[AES256_GCM,data:SWq9gAdvKyL2uYO0x/dPwozIhTzkOa/1yY8=,iv:7SYAceKt542UkfTqU6NgFN4lbpMCqtmylnndyRA5wNc=,tag:ihQt/66X0rB+RyqHWUHMZw==,type:str]
        volumeAttributes:
            source: ENC[AES256_GCM,data:zwDECMgT2G7TOycn2Gz+dB7wcbSlpGogJRuJXQ==,iv:Nm+zKg6wx339LomkzdCf/Kzgd352xff4AiiZmyU2Cho=,tag:p0W17H9GyjhAHQfFo5KfkQ==,type:str]
        nodeStageSecretRef:
            name: ed8-creds
            namespace: edatw-ed8
    claimRef:
        name: edatw-ed8-backups
        namespace: edatw-ed8
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dVBwUlU3dlh5VGtYSTNj
            U0xjamMveFd3SzliNkQrUkdFM3RMR3FoaGdJClkwQ1ZtTFhyam1oY0ZFUVZFaEFE
            bW5ZV3REdWZpaFo4a0hHNWcxNEtGd0EKLS0tIExiUXU5UUVoUG9uQWZUbkt3dnBk
            WXNNWG9xekwvTG45Wmx0ejhrZzlmOGsKnWQyEjnq4JCEnwrSxHoaIUoPVvo1Hvjy
            E4VmJXsnRXHF+kbo22hIn3aDsQ8k0ajMTpxzlhcIMjFJoClK8OLwmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(volumeHandle|source)$
    lastmodified: "2026-06-18T01:36:24Z"
    mac: ENC[AES256_GCM,data:/Z7NcZqiRpcDmL0q2h2CQQ4xOdiekhQdKyySE2LwabDsW5OvnqsECgf+mOIxzG4x4lySF+AzH1Sohhj3q7FW/Msf12YANzeVUQlXc6/3TXMD0wENPamvs6ZyLhTuWPOAEiwa6eRlvRTZU5Leqlqc4zbTypiIvkCjbw+BPXWseVQ=,iv:vRY9voKGYDWXUfwOf8mOXz2jb+TR2J7onP4QfFOrFm4=,tag:D8xjXXJYhy4dYXQcZSGijQ==,type:str]
    version: 3.13.1
