# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ed8-apiserver
    namespace: edatw-ed8
stringData:
    ed8-apiserver.yaml: ENC[AES256_GCM,data:4yaqpkugiYn0otpI34qEFvmJJ6riYNK5BJ0E7WTEyoNPJOa4nUeodmjBPrDJR7Lo2LoCbSNPfYyK2zL5qGKEsQHNIQIpDXEVLpGKHXU/47fNYmxrMfLcAe40aDfrWhdeQQXr+NZXZQBO26sFPKFWqVy7uYoQlUxStQvf2LKjq+lE2wJCxL+MupSXGxy+AIhOdSgAaM6oZffz4FfFiCFmGw==,iv:NXou/S6bFF51tJbOxlLL45aQiOyFcQIO5xHJ5TsxdOo=,tag:WkktsDyX2YfSwXVm0mN0nA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRUhJT01aNDQwL2RIem1y
            SlEyaWtSdmUvYmFhSGt0dzFSNDBPSnJJZDNjCmxvY2FYSHgyeEZDNFZsQ2pUU2xE
            aFFQVk95ZUJkUFgwTVFzSnFVa1UwdVUKLS0tIFROSTI1a2JCWlJQdnpBZHcyd0ZW
            MXBwL09DNzFlK2xnS1pZbWZhTHRUOWcKSutnuyVkE+7p3NH2Nq2+2kdYBtlUKwTu
            nN18e6T9vf543PkSKx0rwdiGpkVSN1JY0lE06ssddAjC4zmIrslzrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:32:06Z"
    mac: ENC[AES256_GCM,data:lxET7Ii2I20vLigId3ghgaBU9z7Ry6cVUM+O8ZyzixYXyoTzRPKq1albst3Seos7lxFiBm/67Z0WnfOCSMwayzI2TBrolK87CKwPRDPhVWON5JS60CgRkUZgousD0dW9zsON29Vrtm7DwSw+f//elf3Fe1xHn+mr2YOuDTOpbK4=,iv:veKUdZjTOwOsptFNWhv3oEM1yuIE90kluxGBGdBqFy4=,tag:/L7koBq3/qG8bUFQyHdEKw==,type:str]
    version: 3.13.1
