# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ed8-creds
    namespace: edatw-ed8
stringData:
    username: ENC[AES256_GCM,data:C4JF,iv:US+TLiDny0yHgHJpxVJB1Rgy/YB17IZkpUv8DXA13HE=,tag:4LJahNljpfL/w+uS3TezdA==,type:str]
    password: ENC[AES256_GCM,data:hvG/NEoZc1895cIx,iv:1SFk7WvlkqcwtOXNLIE+CDujEDmw4lSVC2rve0jJCEA=,tag:yZIhmqXokAP05NLj8nZqrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMzdzR2d5TDJLc1p2L1Fn
            VnBCS3BraFFnN2ZnMnloQlhFY3FQQ3RYWUNNCkJraTRRMUFhY00wWXFmWG82Z0tJ
            OFZoMVlTei9DNkFUYm9PS3FxcmpmQWsKLS0tIEFQWGcvSFNDVUJVdDVSWnFPTDlV
            bEFtNUJoTXBiYWx5YVdTMTFMZGFEbG8KGaU2TR0d9NAzyXj1ePVlbD9ornDbkuog
            fJt2MCqJXMSKJizx5ZS21Y9zMU7FAP3FUgDBTh4XsDhrlY5xFBf5sQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:32:06Z"
    mac: ENC[AES256_GCM,data:ihXmmKNH+uavC7MN2ZvGuEv2aarSxl2CohTUeMXlC02FVKKrY9QS2kHwFxPs4vBTt9KB59E0CKvGrO1lklyJrOtnLvbGs3+xOl9X0Rzy1Hlo5RxIsoS5vt3wfrtmb1wNUGJ+ehZcajWjjkhutZzv4TYqq89VvBuYDI5quPmRsDw=,iv:sbqlUH9i7O/Z+mUNg1wIFBsq+/6y+eMlmGRyeXD45mY=,tag:AEf0yjA1PEt+OoldaBWjNQ==,type:str]
    version: 3.13.1
