# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: github-registry
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0PeGoxekk1lbdlKD/4P4GAhERV7/l5DwM7UA16izEc2OvA4FDMcJO966LhmDlSUgOMbcOjaa8g9Iutbv30rdd8nm7RyJXmWxc2xi/JSwVc3xYCgja/blKfIognAh/e51Nk3+81TBRko8LCsDX8XvFi1b1bLs8MiMPE8eQmv/AhFgbLN3+kZv5fwWNt1Zi0+JYG7ozGcLi3FGO5LdNFom3RI5AyndPvP7FX/sBIw8mbXpiGVd+BULQCZGuXJQOTO+dy+rDkeJGq6H72jn8mrnstXDA1LoNmErDgWtwBYgGkHkMWpx75UijpDXh/MRXmyG9DD5rRrB7XIB5R/6hN5i6egTMwXNSVCzPq3Mtbu6yoDI9xFxINVRy/04J1BTjYntgfVZFIgOxXr+fLV5,iv:dN/QumSN2qKauHh1A6PTO7LjymMSiIjzgSaq0ETu8w0=,tag:lHgdCTFep1RGcQ+l51mgkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMHV6N3pBZFVxTnRFWVhR
            alBqY2pUSy9rNVBXUXI0NWlaYXF6Z3doOEJzCnRCU0FmeE5pSER2RFVEUExjZlVH
            ajRLNnlnZ1J5TlRCVXNFL3J5NDJUckkKLS0tIGliOXJXdThDcDdFbkltKytTRXpi
            R0pZNTJJd01tZDNRMWVvM3JVNWJhaHcKb/NsrClak6a/ddpeNtlsU/JTk7mL1k3u
            Y+P6D97WzTx1K/U/nZgc/IYu4rC+MJjaQOric5wGSWQrFXxWWbJ7lA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:32:06Z"
    mac: ENC[AES256_GCM,data:9c6VsKb5GbWwcprdgRVUVzp/FE1grWjiOHudQKpspeAl0hekmg/4rSoQsG37AQIIiQkizCdtWLWijcxf27DqtrEFs0sSkGs34vgTuoMjxrq/lr2zRs6fA5xQfYTcn8zdZzgN6V8Vo3YTEBA2IflSULDXpURR7HkCfrl+VuintX4=,iv:gunzQa6XMG8wo/3GeEUB0JUZTwc0iUsdTgq3Wkl0sIc=,tag:HjX1hhC8dRUKUroJBDeSJQ==,type:str]
    version: 3.13.1
