# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ed8-env
    namespace: edatw-ed8
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:fptK1tk0NeKKKg2g,iv:eLUcWqUbRmwDyq/p7Kg+2kboawyzOqO1FdWXtXXo+B8=,tag:za8mCKpE04+HaMwhekaBfg==,type:str]
    ED8_BACKUP_VERSION: ENC[AES256_GCM,data:GrImqi/z,iv:FbIXUPgCz9NWFaFpRxYxVgX+2915TC3E6iLDx8MYfj0=,tag:3bz+ORzG6doKXY3tDE4PzA==,type:str]
    ED8_USER: ENC[AES256_GCM,data:ilTB,iv:l5+W1QebD3Htl63ewp4gUV0R/RPaQGQdHZvE7bj12uQ=,tag:5IsRBftC4zuuuUzYMYjnfg==,type:str]
    ED8_PASSWORD: ENC[AES256_GCM,data:euY9lsIRoig=,iv:9Yhj8pH22vU5L2gEUOzacNPgByqp6uJHwqKvuWat3I0=,tag:g32E4ARU2E7y3fD0ld45QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6blhLQnJsYk5FekxIOVJ1
            TDUxMTQ3aVdhY3VjM1VhajN2ZUdVaUh6aTNVCkVqTkQvRzY2TkoxSkRKcURXYzNF
            bHlQbWVWOXdLNUhVNlNLNTdMWk04T28KLS0tIFFuazBBMFVIbWxIdzhLMCtiTXR6
            cGRQMzArVGNMUHYxQVdFTFl3Tzk3NXMK89C+Auo3OqyZ9K91kScAWF5CVI2hJj2i
            eCR5YVYyp53RAHWOy1qMFsJ8CKIjXX9qCWoeufGXc0r7mcXrYg7PXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:32:06Z"
    mac: ENC[AES256_GCM,data:wnQ06lPsHM5oyZabs4eq9t4khiVTO9ZcabNRZu4J009qHHq9kuU/sTq9OddeAn6nNlMdeRYSpX/wIWY0l4qmbfEWV7uF2vITgZOCAE4wuhJ68MC54eTD0uOffup5ejyVsqRo1QLjW82g1KRGcXuZ4Idvgd9MR0006+IbVdVsbsI=,iv:fS+X9wPribjpmRY+Pwk2BPIPkVEWB+ss1YOr0P8LxBQ=,tag:iJA0InwuGjhb0s9VJMHdtA==,type:str]
    version: 3.13.1
