# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ed8-cli
    namespace: edatw-ed8
stringData:
    gaplog.yaml: ENC[AES256_GCM,data:nvVH3Iwhgs1TEA6zYYYLMTxbndpLvW0dOEvZWABz+E5gWnRBKHuDdhhChfCI69IkeGtQzXlN1PhcsFDq9StM3WXx6D1lWJcaT849GNpIsdd76bNL4mc=,iv:P9Bo0woPEhvBRUFrWW/RpvYDJfn3EiUPYVqJf2hX6t0=,tag:dshXQFYNplj6klAFCywKZQ==,type:str]
    ed8-cli.yaml: ENC[AES256_GCM,data:TXr5AmZ7q2NkA3YWfl6JFOSxNFXZvZu26Y84xeiTCEjZSa+LpsYXx90m9cw7qxrLn7TQ3y7ApJA9ROXS1XyU0/rN2miYESpx87N/WB12w/5hQayghGFw30NJLULvakc34ePjq3ieGAfB4Z+YXyDCGjYSfT/a442Da1UVZvR6w092E4jgVsLlWTOFBGo=,iv:TDyAvyxw4CBO637bFilLfC0xU9W4WcmKuSjAJS3AqOs=,tag:yP8DXcHkoKF+6/5bFVjOhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZHlUdTVPbllFMFB1N1dj
            OXZONVp4ZlFwOVFyVTFaYW5lMWFSMW5IemhzCjBmT1Q1YWZ5eWVQaVAxSjE2ZUNN
            NGJiSFpGNWxWSlRZc21YODUvM1BDZW8KLS0tIFNlY1BOSlY0Z1FRcDZxeDlNRFB5
            Wkk3REcrQi9FcVdzNkR3WXgvN25nYlkKk7vF+mT0wZXsh9tkM2hn6MUh5GTCwftV
            wzZuzzYzp4T1oBkXdq7x6pF8wlfXs5NWic7a/E+W9c+1xsyLJ+z7kA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:32:06Z"
    mac: ENC[AES256_GCM,data:Q66NU2I2Xp5/Z3ezU74Zt9Y4PXmwWTsqts5Ij7z4NubU04zYMZVl19bUs98MLgMFI/45zrEuxgRZNdVKhYn6SN/UrlwkERu/xOSBxD7vjrEfThjgZuwzD3h8dySwBZn6t/zQk3VWnn471ZY3JlwZK9Zqe0GKRxbwkMxPCEtP7g8=,iv:ksFpL2b0pEkZ0Sb0u0JkWvjWIMQM/8O1XfIH9/huxe4=,tag:MRLdAbgX32s4wyoL7e8DMA==,type:str]
    version: 3.13.1
