apiVersion: v1
kind: PersistentVolume
metadata:
    annotations:
        pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    name: edatw-eda-backups
spec:
    storageClassName: edatw-eda-smb
    capacity:
        storage: 100Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - dir_mode=0770
        - file_mode=0660
        - uid=999
        - gid=999
    csi:
        driver: smb.csi.k8s.io
        readOnly: false
        volumeHandle: ENC[AES256_GCM,data:vjytAo1IIXiIXJg/8E2fvWigDg4eACezS6tE663P,iv:QJx16gPZq/ZS3LcA2jSiSudkm5fCHM0bMf7Dcg1nJWE=,tag:JKlHoKYsnUJKbTK0dZoJZg==,type:str]
        volumeAttributes:
            source: ENC[AES256_GCM,data:CN4PIFZi2ZMAVyJBvp0Fuvr3LCT10cPo46KphfhpNDg=,iv:TY0eqRMZlneg2YMvIiJ3Dfbw2tayRHYSa/qS2pOSyvc=,tag:8AUvdTbh1TXNL+ytXFemSQ==,type:str]
        nodeStageSecretRef:
            name: eda-creds
            namespace: edatw-eda
    claimRef:
        name: edatw-eda-backups
        namespace: edatw-eda
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUUViV3JLNG1xaDJTVjVk
            cUpoYWRTOFoyYml0eU1maGh3TjIrR05qNVIwCllIUk1hTEFsdWQ4TDVhSnJyNmUx
            a21nZVR0d1BkdUl3Z3MvTUxnMXVqK0EKLS0tIDVBYnpiSmQ3YUtUSHBPWmFZUzgr
            N2xXYllicmNNdWQ4RmZrWjhqcTRpOUUKA+wNDf7pgXOeOsiv6ikmDwK9xcF4t0M2
            NTy7Q8CpAKzJfV/VL+3J7vB6AkylJxb4XfU5koMzjItFVqQgb730Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(volumeHandle|source)$
    lastmodified: "2026-07-07T13:44:28Z"
    mac: ENC[AES256_GCM,data:f0tEAaKyo4krRK+MqmG9lx/MFxRuI28DxKOZhQcBSSGSWVoLfbqZdSO0NQbNoUuChiucVm3UEJEDav/sqRAfexAnCOdrc8oUEqsGPuhvxBMWvAPCDStCXo3FDq17+M6LkVPddfz5yd4IrzuKpTam5znw3YndhlWE28GQhOGrw2A=,iv:8W/hmwHZR6hvUBZ4/5joG2PlArLhAPXtMFLOd1uhg1o=,tag:HCd+690A6cPVVdRomJyvcQ==,type:str]
    version: 3.13.2
