# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: github-registry
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Nn/3wgGiM0oyj2Mbby6Ytm1rRDS/K6OJWF1pABU/XWb0JNO4rdSfGBPXyet7OyR8Ky3qH3WT6bNDL3EDJkYMBBmeIJvYZuN+Fc2s9Xp3+v+NzuaKau+UWYm6QWL2p2bShL3Om7rNw/ybWEJHQ18M74IAQuIjhhptQ+gGj654fQUfEhAZZenkhuAkOXdcDZmeLW2eFkO5c1gvMeQ+8rI8/okksIfvJBlH9Db5JyGtx/6UOICRrG16WgHEE/U/K1GZ4lOj1cUCSQ5g+sP6C+GwPw4ISE/FFOj45zdqdPIz98EWqckph29EyRhytPaa17/2BLBS/RFEVT43SHXx0EAd70JkYSeiCtHmaLgPUzavP+SKnpD1jf/e9lxFpgAa0IZJ1/FnW30hUUHeuT9n,iv:xJqyQasPjnJTSBT4+jr6WJhSHBPI0ezOB6VqRvAzcKQ=,tag:gOF2dLl7ziTBwxZmsbZ6yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMVRrYUw1cm8xWmJtMHMv
            bzRjVVpDaERXNEN0YXEvRXhKbWwyS2J6YkMwCkhGUVhqREEzZVBidXVkWGptTmg1
            QWFDd1Q1YlFESlFhbkcvVGpBQWZ5N2MKLS0tIDFuR0U0VG1rcFdvWWU4SjB3WEd6
            cTJTVUZuZHB1RjEwWVU1bjhJZjlnbTAKtkNRxjhpzb6siFJpQFA7elHraycQWNeE
            3wsuqaGvAXmwjK5/W8xn0L6TwsldUoS3F3Vrp/DlqUq2PnVoNM3/FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T13:48:59Z"
    mac: ENC[AES256_GCM,data:VHTg/G/tdatirDYPXTPGHbaxiJFp9MqcyEJaCbn/bnHlC3xYqba3LiHfW3+MInqY0FPJnq+0xNZ/qhEJ1j0r4yYVWYJ6o234TTsu9p8t0HTr4pTE9OkisQPiMBsB1A3Y/dCkYVvOPhFX1dh+2y1RWfLLg9A9Zws6FpKjeuknAkk=,iv:3GualfO2pSgT27gtmrL1Oq4OyUV4XmwzkImUOROLl6U=,tag:+D95Q2OUNgpKNWIIECGYJg==,type:str]
    version: 3.13.2
