# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: eda-apiserver
    namespace: edatw-eda
stringData:
    ed8-apiserver.yaml: ENC[AES256_GCM,data:mPw0BgMj4TWqYPf1DJXjHBkJl04dQ/AM6lT/gqL4bbYF0FvfDB9TIq8zlqjMZHAZM/CLKKmiCdMD/N+3jdT/iP79Jk+fAMnmgiZ64P6cTXJcxIxi8FPj/x82sVSI9B4SFPR+vOKRGVVzqUV/WQdUfovZ4eJLnIW/tvrXd94RrqMckIxuprALz9lNhmyCa/1+tUdPNwJfYMx2gFHcegiYFg==,iv:zWiBHr69+hZj5DWXrSxwhMpdVDRLi8PlXn9BXsy63ro=,tag:BdzbdPHI3/RP5CuGJ0N2Zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzekF3VXNDZVZKNkpBSUNk
            dkhHQlJTMjFUR09ETVcxdWNjamJ4NGV6MnprCmpvdXVDVGVvdnlwbWYzOWdlRVVs
            emI5c05SZEJtNmluOWlFemdBTVJrN3MKLS0tIDVlVTRHVzkvZEZtQjExQjNSN3E0
            U0Z6bDRBcDBTeGJnZk95a2NONThaWFEKjQsbXNCpq0rO+cWODYraHxT3se5OiNw4
            A++rL7kG/ZURMpNBOIuFV8W+wYxp5Q1zo+d0giAAupRuBam/l2Kvmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T13:48:59Z"
    mac: ENC[AES256_GCM,data:qM1An6MQzcmIniwTLdogo2xyDOh9P8JYFV4uSr/lCck7j/fyrk4hBmAtkXQd9xjiO0QmdbIHHFp895pXrWifNnn9wJAAXNsIW6H80BLhc58o34mmGcozoEG1laCcjtRMRhiv7XiQCasNuDfEERmEY0PPCRaomD1vl8FNlENUopo=,iv:8ev9rGZd6BJiREEysagR2UkmGqpt+Dmp84HoNDsWbRw=,tag:j6eMiAeHYnDQPWQsJwEwLQ==,type:str]
    version: 3.13.2
