# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: eda-cli
    namespace: edatw-eda
stringData:
    gaplog.yaml: ENC[AES256_GCM,data:BCPthf3oRYrGl8j0iRkhaJLFbpe/Z8UJQAnlmXKfvFh+AxGrFUAvQKPGN9T0p5L27Koxh50SO0Fl6O6ulMgHBUsyixL7NxcrOVXGvSL8Wz/lPuLZvbk=,iv:xZhjCOMb989m6L76vAffq8lUguIXDz3xhLUNn3FeupM=,tag:nHGhmD7pUoDJp0+cZjyT+Q==,type:str]
    ed8-cli.yaml: ENC[AES256_GCM,data:bWQGGgx6PiIEIaX1u7b3YgN82lnUCszLXgeZxtrrcenDfTvTCACRjHN0u2ikPg+eVlkHwHKF+/QMTRjmSMbRTdGTZ3JP4yDb24fpUNi2KWSSbLgHnmcprPVupXH4f5g7FvBpjkpWDtXFOSxMh0g6MtvNna8HtoYa67735N9Iyco5vXDNl7uhmibLs5U=,iv:tCnta0n+yfOviSn1Yc9vCtjtKgsa57WPRW0OJaMcD0U=,tag:bouehL628PVRF4Ob/5N1mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TXo3elFTYUl2YUZubTUv
            ZDMvaVMwTSt0QXZHUEl6SnhlbGVqbXVJa1E4ClNCYU9ZZEtGSlpoZDN5VGlhbnN1
            QmxPaG1ncGVYR1N0bWkwVk8zOTFRRmcKLS0tIFcxZm1BNXR5RldmWEIyQXVrVDJO
            TkJPMWIzM2hTQXBEQ3dEZ1hpeGQ4TzgKiFZ4E4FyLoSfrPkjaRaVFAY85Vi65TMJ
            p6vnUgeS8+YEPdkEczjqs7h4NUQ5/JE89xG9OvEeSjQXYt1JzgBlNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T13:54:58Z"
    mac: ENC[AES256_GCM,data:uee2c8VyhMJf9h+PJy7SWmQFhE9NG8UcXMxt3kTGBjsg7ioCsZ7PdwmMaMGwIML9N7o5PGkqF8muEJJ3OZHua6gXvQHmxk5jU5puskOiDX5iJqDygGB59UlBkH63xkPEj8jzcwFCaRx45cSpVS2WWbtyhAjdvbpwYDhKdXuQc40=,iv:XpS8NLSaxHaKQHFxjchXeearmbgoA/oUn9oioKbV5SA=,tag:qzSaNbi6OSt5aOHu9FOLcg==,type:str]
    version: 3.13.2
