# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: eda-env
    namespace: edatw-eda
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:3YFJV2vrquueW60D,iv:LNpek0fkTQV48ePiJCkiqaD8jjkvgSomPaegQO7UBNg=,tag:ymCroSwwHNL8nhug1Zpcrw==,type:str]
    ED8_BACKUP_VERSION: ENC[AES256_GCM,data:R5O52wc1,iv:dXd94fYSEfXBVV+ZH1GkFyPdGl4q8D7hDD2QBaw071Y=,tag:+UV8IHwgMpX0OyIuWNRBRw==,type:str]
    ED8_USER: ENC[AES256_GCM,data:+FXm,iv:Ypu3fykoeYA0HL82QPeDuVlggoAvlGprp3kqdXrYyys=,tag:T5ND4A31S60WWc6NCLhXeA==,type:str]
    ED8_PASSWORD: ENC[AES256_GCM,data:fPqgIIsMbBs=,iv:rgRxbgIp5APBzQO4QuCFgfsfflS+MlGodYym/h9A0js=,tag:woNnxJbqZciAJ+n2bjApfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXR25XUjZVVGhYZDdKWkpz
            YjBJQkJCZGlPSWFsc2VtUlp1NXl6aTM2MlRRCmdFM2M3WWUvcFRGRWFFWDh5MU1G
            MjI5WFh1cTBqWVhFU25Jc28xQXZKZkkKLS0tIG5BUytFMGk0KzBqOVFka0l0cVNU
            NG12ZUxNMldkdFh5V1p6dlJycFpsdkEKIe3ZK/6B1s4dlH9sYNLmO04FWn4xmlK3
            ZBtTsQO5C9oYJe22zFm77iXSZjVM/bQH6B0J8Nii7+WxPIAexdI+Gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T13:48:59Z"
    mac: ENC[AES256_GCM,data:zhyYaNnLhzf+v31lsNWOblLjQDChAWFd6bo94bLDgCgxoSKE/dnFFIPVHXHZ9oJWFMVYqU5dWXrw2n1+FGuNSOOeZ/icx5OmRE7/+v9UWsGRAml4nAefpBom84OyUdHZKM+++D9x8rO1ZTbYZpWGJxys/8zaJtFcMUR1FQ4YbGg=,iv:LlMGxzHXbPfaDepKorKvANw/IcP16oFg8naz13qqnq8=,tag:HacKZHoIben1MYoh+V/rbQ==,type:str]
    version: 3.13.2
