apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-eda-credentials
    namespace: edatw-eda
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:I16WaOAnryg7fPefVeG4lAj+glrofj5XqAJs8/Z+IDFrrFDLY5SyrZbyZk90qJZ2jH5TKJnEZjnAFBrtYYyZqzAqYYl1IDFi9+3nTWVBsnHVGRSGTG2pQ/doAHtZV3C4ZK9hg+YPOzODTko303o5Xlu62MyNC1ff5m2jwDan1HuPJtzPGon33F7uKMYySoeSMVetvDp69nEiYMktqRGB6Eo/IJuWGBrvUi5VlzTO6wFc6/jZ,iv:1vm45Psl4i+83Y9BGsCgHZzOXkoGz5Xl/TqgUjM1AWU=,tag:YM/+MHo6LAmYK7optjiBhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNyt5QnA3MEN4K2w2N2NN
            ZG91RS9jR0dLSjRVTGlyNFVjTXBtQjUvZ1FVClJUcnhsbytxME9vYSt0Q3BDcWVN
            ZHJPN3VJTjYrNTRoSVcyWTNiNzZsbEUKLS0tIEJjbFNpbHAwMHdNaXU1RjRXUnpI
            bFdiNmVrTzhVQUxnWENCL2lSaGtVejAKjmIsVMYEUuQBS9cdRB+Lhg0rAWPbS4dj
            3EroOgv1qoysWU49wwBQnsCADgl4fEoWFueI4kbtoHdjWCdQ0xEwBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T14:54:30Z"
    mac: ENC[AES256_GCM,data:4mK0JgxujTGf9BQgRW97EKTSRaxXqKVHiXRN5LuIXOoJU4jY+qA0xW3HJfjMbTI0p7ybMYPdIGtwHYiI3rSrt5OZF/R+7iWDdboeWsnhFTbzxiMdUtwunftYt/WmHzMq/fK+q3J7kojFGULVBjxv3dmWxmY8reZ5O/wuWtidXtg=,iv:7aiJAosE3kgvk9e36cc/NFcBCvu3qZq+/0irS+OfPRc=,tag:x6TkZQvkHHoNkBn6xqZKLw==,type:str]
    version: 3.13.2
