# reference: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/#Secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: eda-creds
    namespace: edatw-eda
stringData:
    username: ENC[AES256_GCM,data:nU5s,iv:pDtTmVQzb4NkLGtM0pvrErgmnQSAes5xupCGjhXZLSs=,tag:SOojxtsvR4aGcozpV5QZAw==,type:str]
    password: ENC[AES256_GCM,data:LXLhnCpK634g51bI,iv:KYG15urvvKE8N1XzC2q1yZpMJ2fYIb639UcY9JxF0S8=,tag:6ZCToJoNqJm4yT9qLA9wQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUM0hxWmloWTFjSkJTMWRq
            Mk5lclRLOTZocVVaSXJuYjFwWWs1RWM5WTN3CkxlM3VvaWhUZllCdUZzSEZVcDJ2
            OUZ4UjU2dkVFTlJVTXdNcEpjcU0vek0KLS0tIEZyTHBxQnJmT1RxUjJscHh2anRY
            Q2Z5TWhxNWhpbVpvc2ZpVEswVm5nMmMKR2FSE94F0qRsUInt5O6NPpAK4xgy+svp
            hEFS+qRWih4IumQK1PU0X6A24kW0dPTfjumLVLaPLGa7eIg9Vw/teQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-07T13:48:59Z"
    mac: ENC[AES256_GCM,data:rXl2Ia4KXQkqts5UHFMDDxYO0LS5aHm0POoJWNITfXWQwOqzSFv/1FCRDDq3cai0Rjma5un6dovt/ZY1BNPzKAST7zaHXEWOQwxO50UnzHRKtaPchG8K8EG5SvAZoQtMIJNPepFhnSDJY+ssKbmXoRp56K+B8RUw2qA6xs8DnU8=,iv:bab9lIz2BRTXyOnheldWdjqYMqJqlXnqv51jslNPCeM=,tag:WQ7xDkSqSl41hAyY+bPojg==,type:str]
    version: 3.13.2
