# Plain text secret for SOPS encryption
# IMPORTANT: Replace CLOUDFLARE_TUNNEL_TOKEN with your actual Cloudflare Tunnel token
# Encrypt with: sops -e -i secret-cloudflared.yaml
# Decrypt with: sops -d secret-cloudflared.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: edatw
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:CimKSMJNny3xOnSTnhQ5FIfAfLzKnETpz6f0H2fBXxkDyF/ntfqMlpnAzZIc6pLESqEHsoaFriCF27Tuf5uXIDgE+fUEUXPf0JDTgJobKKhpWZ4bVNlQ0jeua9ZKcQ9xRrdmxUomJiNs1d0TH9lipMdQuDnDDCCiEFXzQJG73sGi+m3iRWX0cnzxFjbO/NRdngqZkuNB9zn7B8BkSesvgaG3EMZqGrAzpIdmhxc9ooc3vSrB,iv:Ygjev+jb0y/jAtI547uRrRhXpHI0CVaFyir0SWhgb00=,tag:78YJr00RYdGF7VnQ1caG/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZampqTnBmaXpvelZMZUxa
            akVDMENKaVpvWTQvZ2EvQkRpdjFYRFlkbGdvCkMwUUYxQkU2SG5sN3dGQzJHTTNv
            WDQrWkZQa080dVJmSHZXbFAwR1liMGMKLS0tIFJXaHpQbGRCcXZKZkM1YVhxeStW
            bTljR3lyUFZWdXhnTjIwWWE5dHBSZHcK3a9drmzIfuGr6lOcwRdRwmMs6Zc0G5j3
            vIjFjbCX7dFF4Pya/BibJb12KYELDY5s2vLp6Lucme6EDeJ9zp8bOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T01:30:53Z"
    mac: ENC[AES256_GCM,data:0EYgQvWgcXMvBQ5qQR+IlIBCtDMOAi5s4BgJiL+ilvoSJevtISE1IY5mhDciBaJV4H5VZbNXDWLSkECLp+UoTx2fwcx8rvfyEFksrpl6LTftR8VXEdROmqvaNDcHFw7wnmioF7zuevLgWsdOV2UWUAHKd44x7XQn+yVrlVZb9GI=,iv:z8Oelq0OzDxGzC30q9F0NgwL+YjvfDXKQJqNTu1J6hs=,tag:iwmVHW2KDc6wPuH99hIutw==,type:str]
    version: 3.13.1
