---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-openshell-ca.yaml
  - helmrelease-kagent.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kagent
      app.kubernetes.io/managed-by: flux
