---
# Kustomize base configuration for edatw-eda application
# StatefulSet with MySQL database, Apache web server, and API server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edatw-eda
resources:
  - namespace.yaml
  - service-account-eda.yaml
  - statefulset-eda.yaml
  - cloudflared.yaml
  - cronjob-backup.yaml
  - cronjob-notify.yaml
  - cronjob-probes.yaml
  - persistent-volume-claim-edatw-eda-backups.yaml
  - persistent-volume-claim-edatw-eda-data.yaml
  - persistent-volume-claim-edatw-eda-database.yaml
  - persistent-volume-claim-edatw-eda-image.yaml
  - persistent-volume-claim-edatw-eda-notify.yaml
  - persistent-volume-claim-edatw-eda-pdf.yaml
labels:
  - pairs:
      app.kubernetes.io/name: eda
      app.kubernetes.io/component: eda
      app.kubernetes.io/managed-by: kustomize
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/
configMapGenerator:
  - name: eda-script
    namespace: edatw-eda
    files:
      - scripts/restore-entrypoint.sh
      - scripts/restore-logical-backup.sh
      - scripts/logical-backup.sh
      - scripts/physical-backup.sh
      - scripts/exit.sh
  - name: eda-my-cnf
    namespace: edatw-eda
    files:
      - configs/default.cnf
      - configs/eda-database.cnf
      - configs/backup.cnf
      - configs/innodb.cnf
