apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-openclaw-credentials
    namespace: edatw-openclaw
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:HSqWdiztlKOpsENaFokqTaoobijBw+pVQ3msewC4q+mh0GUcG05BXo8ldHFLXcjg2M7OPrafqModcG8anE7443rp9ybduODiROlBt53S9JartjGpM9IEmhfLovaC6ijqn76IcX+FzGF4xWb47lLrVDL/fLntwyC/5zPbzFxfGAy4q9fyhXigMR73CeK3Cl5kKOnBXof2lqj4RjkOF6G2RgWFZNEzwA6Rg9RRGcZ+YRGS5ghr,iv:+de0AZ40KgJCQgfBHvel95ACNTR+eZfBTOb5VWacVLQ=,tag:uikLPsfMM6TrNFkKe6ECnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VnA5aUc4cWdNZjlmTFVD
            dVViYzJZaXVMV25LdHd5ZXBGaDErKzJqNFFjCmhmMTVheWRKT3RMVjBZZURMMHU2
            bGJldTFadjdDM0wxaFpRc1JLTXhlc0kKLS0tIFB4QUNyVmRlSmFkaHNvamVNYVRE
            aCtIUWpHdUJ1Wm5QZXU3V3IycUFkZTAK9K9hLpIIBNroktjwHi0IrWY9A8dpweYd
            mYfJRNFQc4NqaGd8qqjLlfhKsdzZJJNtykOYFmy3Td84IfNWxj/P7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nf9ewj7cepndennpcxz77sun7fecph4wqgfkusr53vnkv7g0sedq8qj22d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T01:20:23Z"
    mac: ENC[AES256_GCM,data:Ox+qZ/feEyLPPMzQWtf7xvBMrVmc/KXl3zObw3db/RCt1EOBd4pUmtDDZlNjNFAfhYNWO3SUqRg2RlRC2qrnweO+bWsh9zbolPdw8UBH0v8jU2DOM1Q3T/u2KNH0Dqb4D9ZgjwBD4mVYEV8h9MdMBZ7Qbq8H0hbC0TljEL+gREc=,iv:XIsFjet+VCiI6FgEhxAKvrknHgv15i+AgGNVL0S2cck=,tag:oDQmM96wJipzDJKk8upbKA==,type:str]
    version: 3.13.1
