apiVersion: v1
kind: Secret
metadata:
    name: openshell-ssh-handshake
    namespace: openshell
type: Opaque
stringData:
    secret: ENC[AES256_GCM,data:iiiSAnL/uRtgDV8SE597O3XvAB0xGFBFC9LwPXf69cw1kciq+As6ziTxd+ygxi87SyjdxQCgx4H75ajGU4vcHA==,iv:+G9TfbZpJ3h3sJilvDlOmBl4jIyeU1wN4P7zZ5293jQ=,tag:JdUtcVOZDVMU2dNG297onA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SXEwM01SYXBxWnFDS2Jk
            QVhvbjlNWnQ3M3ZIaThsTDhYTTlXR0dOWVFVCkZ0NXdKNWZZM3ZXV1NQY3QxYjFN
            MngyNU1NOWFwWFVuUE1tdmxEdmk0aTAKLS0tIEZoSFlJenhTaUhtdW1NUHc3KzZS
            UXlQOEM0MWVJenBudVlnbERrWXcvWTQKYuLXWPmiUsFdZ8jH5A6aYx8emifaLpWf
            auP6uAgUXAhdHp5RItCuBnZFhRiIHkLaQr4wcb6xdApeGtUZXdQLUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age142yu9a74xm8vfls25jvmdvw0c3yrcsvdht0ah9yu8cysya2qqyaqmg6y0a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T16:01:47Z"
    mac: ENC[AES256_GCM,data:sglh0QdHCor65RlwTg/a6sDDTqPnVVwRspwWmjqcITs4Ipat9C0uqIzw8mgYzbx6dcOfEgz4vyFNSHUXCyqgXPSFfD/UjIGm5Oi3zBwaBt9jnWpsJaazhTK39yo6EEZi8AUTMsjaQwVgErbQTKApvVsSBDanlJFZsMAQLZkDnHg=,iv:3RBKKcEgDoU1sAg3An/OaQXWDVJNe78JQh2Wc+VVGQg=,tag:E3vHFBUo9dbLXbnfjrwNMQ==,type:str]
    version: 3.13.1
